### ISSUE TITLE
Sorted sentences tsv file not generating

### ISSUE THREAD

**Issue by yaoberh** [Vuizur/tatoeba-to-anki#1]
Hey! Hope you're doing fine :)
Just stumbled upon your project and I love the idea!
Problem is, the sorted_sentences file doesn't generate:

```
tatoeba-to-anki/tatoeba_to_anki on  main [?] via 🐍 v3.10.4 
❯ poetry run python3 main.py
Traceback (most recent call last):
  File "/home/yaoberh/tatoeba-to-anki/tatoeba_to_anki/main.py", line 91, in <module>
    with open("sorted_sentences.tsv", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sorted_sentences.tsv'
```
Hope you can fix this!
Have a great day

**Comment by Vuizur** [comment]
Hello, thank you!

I forgot that I had commented out some part of the code, which caused the error.

I worked a bit more on the project and fixed some things, so you can try the new version, the configuration is now done in "config.toml". And the native audio download from Tatoeba should now work too. (You only additionally need the sentences_with_audio file from tatoeba.)

It is still not 100 percent finished, but should work (in theory).

**Comment by yaoberh** [comment]
Working perfectly! Would be cool if one could choose to download the audios or not. Or alternatively check for audio files which are already there if one's already got them :)
