### ISSUE TITLE
No such file or directory: 'audio_files/8374092.mp3'

### ISSUE THREAD

**Issue by yaoberh** [Vuizur/tatoeba-to-anki#3]
This error shows up whenever the program can't find a specific file, even when one specifies one doesn't want audios in the config.toml file:

`FileNotFoundError: [Errno 2] No such file or directory: 'audio_files/8374092.mp3'`

If one creates this file manually, it will skip it and notify that there's another one missing.
Maybe it can be skipped if it can't find the file?

**Comment by Vuizur** [comment]
This should be fixed I think.

**Comment by yaoberh** [comment]
Working splendidly now!
